version: "3.9"

services:
  api:
    image: node
    container_name: rps-api
    env_file:
      - .env
    working_dir: /usr/src/app
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
    networks:
      - rps
    depends_on:
      - db

  db:
    image: mariadb
    container_name: rps-db
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - rps

  adminer:
    image: adminer
    container_name: rps-adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8181:8080"
    networks:
      - rps

networks:
  rps:
    driver: bridge